//mport java.util.*;
public class FascinatingNumber {
    public static void main(String[] args) {
        //System.out.println("enter your number: ");
        //Scanner sc = new Scanner(System.in);
        //int n= sc.nextInt();
        int n = 192;
        int count = 0;
        int temp = n;
        int p = (n*2);
        int q = (n*3);
        
        System.out.println("below are your results : ");
        System.out.println(p+" (is a value generated by multiplying "+n+" with 2)");
        System.out.println(q+" (is a value generated by multiplying "+n+" with 3)");

        while (temp>0){
            count++;
            temp = temp/10;
        }
        System.out.println(count+" (this the count of original number)");
        temp = n;

        int divisor = 1;
        for (int i=1; i<count+1;i++){
            divisor = divisor*10;

        }
        System.out.println(divisor+" [is divisor of original number (count of org num)]");

        int x = n*divisor+p;
        
        int y = x*divisor+q;
        
        System.out.println(x+" (is a value obtained by combining "+n+" and "+p+")");
       
        System.out.println(y+" (is a value obtained by combining "+n+" and "+p+" and "+q+")");

        int a1 = 0;
        int a2 = 0;
        int a3 = 0;
        int a4 = 0;
        int a5 = 0;
        int a6 = 0;
        int a7 = 0;
        int a8 = 0;
        int a9 = 0;
        long tempY = y;

        while (tempY > 0) {
            int digit = (int) (tempY % 10);
            tempY = tempY / 10; 
            
            
            if (digit == 1) {
                a1++;
            }
            else if (digit == 2) {
                a2++;
            }
            else if (digit == 3) {
                a3++;
            }
            else if (digit == 4) {
                a4++;
            }
            else if (digit == 5) {
                a5++;
            }
            else if (digit == 6) {
                a6++;
            }
            else if (digit == 7) {
                a7++;
            }
            else if (digit == 8) {
                a8++;
            }
            else if (digit == 9) {
                a9++;
            }
        }
        System.out.println(a1+""+a2+""+a3+""+a4+""+a5+""+a6+""+a7+""+a8+""+a9+" (this tells how many times the digits are repeated )");
        if (a1 == 1 && a2 == 1 && a3 == 1 && a4 == 1 && a5 == 1 && a6 == 1 && a7 == 1 && a8 == 1 && a9 == 1) {
            System.out.println(n + " (is Fascinating number)");
        } else {
            System.out.println(n + " (is Not fascinating number)");
        } 

       /*  int tempY=y;

        boolean isFassinating = true;

        int checklist = 0;
        int digitcount = 0;

        while (tempY>0){
            int digit = (int)(tempY%10);
            digitcount++;

            if (digit ==0){
                isFassinating = false;
                break;
            }
            checklist+= Math.pow(10, digit-1);

            tempY= tempY/10;

        }
        System.out.println(digitcount);
        System.out.println(checklist);

        if (isFassinating && digitcount ==9 && checklist == 111111111){
            System.out.println(n+ " is a Fascinating number");
        }
        else{
            System.out.println(n+" is not a Fascinating number");
        } */
    } 
}
